!!python/object/new:agents.tools.attr_dict.AttrDict
dictitems:
  algorithm: !!python/name:agents.algorithms.ppo.ppo.PPO ''
  discount: 0.99
  env: !!python/name:agents.scripts.configs.HalfCheetahBulletEnv_DR ''
  eval_episodes: 11
  init_output_factor: 0.1
  init_std: 0.35
  kl_cutoff_coef: 1000
  kl_cutoff_factor: 2
  kl_init_penalty: 1
  kl_target: 0.01
  learning_rate: 0.0001
  logdir: sampledir
  max_length: 1000
  network: !!python/name:agents.scripts.networks.recurrent_gaussian ''
  normalize_ranges: true
  num_agents: 11
  optimizer: !!python/name:tensorflow.python.training.adam.AdamOptimizer ''
  policy_layers: &id001 !!python/tuple
  - 64
  - 128
  steps: 100000000000.0
  update_epochs: 25
  update_every: 11
  use_gpu: false
  value_layers: *id001
  weight_summaries:
    all: .*
    policy: .*/policy/.*
    value: .*/value/.*
state:
  _mutable: false
